#include "driver.h"
#include <devguid.h>

static NTSTATUS InitializeDevice(PWDFDEVICE_INIT *init, BOOLEAN child, WDFDEVICE *result) {
  ACX_DEVICEINIT_CONFIG before;
  ACX_DEVICE_CONFIG after;
  WDF_OBJECT_ATTRIBUTES attributes;
  WDF_PNPPOWER_EVENT_CALLBACKS power;
  WDFDEVICE device;
  NTSTATUS status;
  ACX_DEVICEINIT_CONFIG_INIT(&before);
  status = AcxDeviceInitInitialize(*init, &before);
  if (!NT_SUCCESS(status))
    return status;
  if (child) {
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&power);
    power.EvtDevicePrepareHardware = PiaoipPrepareHardware;
    power.EvtDeviceReleaseHardware = PiaoipReleaseHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(*init, &power);
  }
  WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, PIAOIP_DEVICE_CONTEXT);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  if (child)
    attributes.EvtCleanupCallback = PiaoipChildCleanup;
  status = WdfDeviceCreate(init, &attributes, &device);
  if (!NT_SUCCESS(status))
    return status;
  *result = device;
  PiaoipDeviceContext(device)->is_child = child;
  WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
  attributes.ParentObject = device;
  status = WdfWaitLockCreate(&attributes, &PiaoipDeviceContext(device)->lock);
  if (!NT_SUCCESS(status))
    return status;
  ACX_DEVICE_CONFIG_INIT(&after);
  status = AcxDeviceInitialize(device, &after);
  if (!NT_SUCCESS(status))
    return status;
  return STATUS_SUCCESS;
}

NTSTATUS PiaoipDeviceAdd(WDFDRIVER driver, PWDFDEVICE_INIT init) {
  const UNICODE_STRING security = RTL_CONSTANT_STRING(L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
  WDF_FILEOBJECT_CONFIG files;
  WDF_OBJECT_ATTRIBUTES attributes;
  WDF_IO_QUEUE_CONFIG queue;
  WDFDEVICE device;
  NTSTATUS status;
  UNREFERENCED_PARAMETER(driver);
  // Only SYSTEM/administrators can own the bridge; ordinary audio clients use
  // the ACX child endpoints. A second service handle cannot hijack this owner.
  WdfDeviceInitSetExclusive(init, TRUE);
  WdfDeviceInitSetCharacteristics(init, FILE_AUTOGENERATED_DEVICE_NAME | FILE_DEVICE_SECURE_OPEN,
                                  FALSE);
  status = WdfDeviceInitAssignSDDLString(init, &security);
  if (!NT_SUCCESS(status))
    return status;
  WDF_FILEOBJECT_CONFIG_INIT(&files, WDF_NO_EVENT_CALLBACK, WDF_NO_EVENT_CALLBACK,
                             PiaoipFileCleanup);
  WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  WdfDeviceInitSetFileObjectConfig(init, &files, &attributes);
  status = InitializeDevice(&init, FALSE, &device);
  if (!NT_SUCCESS(status))
    return status;
  status = WdfDeviceCreateDeviceInterface(device, &GUID_PIAOIP_CONTROL, NULL);
  if (!NT_SUCCESS(status))
    return status;
  WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue, WdfIoQueueDispatchSequential);
  queue.EvtIoDeviceControl = PiaoipIoControl;
  WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  return WdfIoQueueCreate(device, &queue, &attributes, WDF_NO_HANDLE);
}

NTSTATUS PiaoipCreateChild(WDFDEVICE root, const PIAOIP_BRIDGE_PROFILE *profile) {
  const UNICODE_STRING id = RTL_CONSTANT_STRING(L"PIAOIP\\NetworkAudio");
  PWDFDEVICE_INIT init;
  WDFDEVICE child = NULL;
  UNICODE_STRING instance;
  WCHAR instance_text[33];
  PIAOIP_DEVICE_CONTEXT *context = PiaoipDeviceContext(root);
  NTSTATUS status;
  ULONG i;
  WdfWaitLockAcquire(context->lock, NULL);
  if (context->child || context->child_removing) {
    WdfWaitLockRelease(context->lock);
    return STATUS_DEVICE_BUSY;
  }
  // Reserve the single child slot, then leave the lock before entering ACX/PnP.
  // Cleanup can acquire the same lock when ACX destroys a circuit device.
  context->child_removing = TRUE;
  WdfWaitLockRelease(context->lock);
  init = WdfPdoInitAllocate(root);
  if (!init) {
    WdfWaitLockAcquire(context->lock, NULL);
    context->child_removing = FALSE;
    WdfWaitLockRelease(context->lock);
    return STATUS_INSUFFICIENT_RESOURCES;
  }
  status = WdfPdoInitAssignDeviceID(init, &id);
  if (!NT_SUCCESS(status))
    goto failed;
  for (i = 0; i < 32; ++i)
    instance_text[i] = (WCHAR)profile->device_id[i];
  instance_text[32] = 0;
  RtlInitUnicodeString(&instance, instance_text);
  status = WdfPdoInitAssignInstanceID(init, &instance);
  if (!NT_SUCCESS(status))
    goto failed;
  status = WdfPdoInitAssignRawDevice(init, &GUID_DEVCLASS_MEDIA);
  if (!NT_SUCCESS(status))
    goto failed;
  status = InitializeDevice(&init, TRUE, &child);
  if (!NT_SUCCESS(status))
    goto failed;
  PiaoipDeviceContext(child)->root = root;
  PiaoipDeviceContext(child)->profile = *profile;
  PiaoipDeviceContext(child)->stats.size = sizeof(PIAOIP_BRIDGE_STATS);
  PiaoipDeviceContext(child)->stats.version = PIAOIP_BRIDGE_VERSION;
  PiaoipDeviceContext(child)->stats.attached = 1;
  status = AcxDeviceAddCircuitDevice(root, child);
  if (!NT_SUCCESS(status))
    goto failed;
  WdfWaitLockAcquire(context->lock, NULL);
  context->child = child;
  context->child_removing = FALSE;
  WdfWaitLockRelease(context->lock);
  return STATUS_SUCCESS;
failed:
  if (init)
    WdfDeviceInitFree(init);
  // Cleanup does not need root's lock before a child has been published.
  if (child) {
    PiaoipDeviceContext(child)->root = NULL;
    WdfObjectDelete(child);
  }
  WdfWaitLockAcquire(context->lock, NULL);
  context->child_removing = FALSE;
  WdfWaitLockRelease(context->lock);
  return status;
}

NTSTATUS PiaoipDetachChild(WDFDEVICE root) {
  PIAOIP_DEVICE_CONTEXT *context = PiaoipDeviceContext(root);
  WDFDEVICE child;
  NTSTATUS status = STATUS_SUCCESS;
  WdfWaitLockAcquire(context->lock, NULL);
  child = context->child;
  if (child) {
    WdfObjectReference(child);
    WdfWaitLockAcquire(PiaoipDeviceContext(child)->lock, NULL);
    PiaoipDeviceContext(child)->removing = TRUE;
    WdfWaitLockRelease(PiaoipDeviceContext(child)->lock);
    context->child = NULL;
    context->child_removing = TRUE;
    WdfWaitLockRelease(context->lock);
    status = AcxDeviceRemoveCircuitDevice(root, child);
    if (!NT_SUCCESS(status)) {
      WdfWaitLockAcquire(context->lock, NULL);
      context->child = child;
      context->child_removing = FALSE;
      WdfWaitLockAcquire(PiaoipDeviceContext(child)->lock, NULL);
      PiaoipDeviceContext(child)->removing = FALSE;
      WdfWaitLockRelease(PiaoipDeviceContext(child)->lock);
      WdfWaitLockRelease(context->lock);
    }
    WdfObjectDereference(child);
    return status;
  }
  WdfWaitLockRelease(context->lock);
  return status;
}
VOID PiaoipChildCleanup(WDFOBJECT object) {
  PIAOIP_DEVICE_CONTEXT *child = PiaoipDeviceContext((WDFDEVICE)object);
  if (child->lock) {
    WdfWaitLockAcquire(child->lock, NULL);
    child->removing = TRUE;
    WdfWaitLockRelease(child->lock);
  }
  if (child->root) {
    PIAOIP_DEVICE_CONTEXT *root = PiaoipDeviceContext(child->root);
    WdfWaitLockAcquire(root->lock, NULL);
    if (root->child == (WDFDEVICE)object)
      root->child = NULL;
    root->child_removing = FALSE;
    WdfWaitLockRelease(root->lock);
  }
}
VOID PiaoipFileCleanup(WDFFILEOBJECT file) {
  (VOID) PiaoipDetachChild(WdfFileObjectGetDevice(file));
}

NTSTATUS PiaoipPrepareHardware(WDFDEVICE device, WDFCMRESLIST raw, WDFCMRESLIST translated) {
  PIAOIP_DEVICE_CONTEXT *context = PiaoipDeviceContext(device);
  NTSTATUS status;
  UNREFERENCED_PARAMETER(raw);
  UNREFERENCED_PARAMETER(translated);
  if (context->circuits_added)
    return STATUS_SUCCESS;
  if (context->profile.inputs) {
    if (!context->capture) {
      status = PiaoipCreateCircuit(device, TRUE, &context->capture);
      if (!NT_SUCCESS(status))
        return status;
    }
    status = AcxDeviceAddCircuit(device, context->capture);
    if (!NT_SUCCESS(status))
      return status;
  }
  if (context->profile.outputs) {
    if (!context->render) {
      status = PiaoipCreateCircuit(device, FALSE, &context->render);
      if (!NT_SUCCESS(status))
        return status;
    }
    status = AcxDeviceAddCircuit(device, context->render);
    if (!NT_SUCCESS(status)) {
      if (context->capture) {
        (VOID) AcxDeviceRemoveCircuit(device, context->capture);
        context->capture = NULL;
      }
      return status;
    }
  }
  context->circuits_added = TRUE;
  return STATUS_SUCCESS;
}
NTSTATUS PiaoipReleaseHardware(WDFDEVICE device, WDFCMRESLIST translated) {
  PIAOIP_DEVICE_CONTEXT *context = PiaoipDeviceContext(device);
  UNREFERENCED_PARAMETER(translated);
  if (context->circuits_added) {
    if (context->capture) {
      (VOID) AcxDeviceRemoveCircuit(device, context->capture);
      context->capture = NULL;
    }
    if (context->render) {
      (VOID) AcxDeviceRemoveCircuit(device, context->render);
      context->render = NULL;
    }
    context->circuits_added = FALSE;
  }
  return STATUS_SUCCESS;
}
