#include "driver.h"
#include <devguid.h>

static NTSTATUS InitializeDevice(PWDFDEVICE_INIT *init, BOOLEAN child, WDFDEVICE *result) {
  ACX_DEVICEINIT_CONFIG before;
  ACX_DEVICE_CONFIG after;
  WDF_OBJECT_ATTRIBUTES attributes;
  WDF_PNPPOWER_EVENT_CALLBACKS power;
  WDFDEVICE device;
  NTSTATUS status;
  ACX_DEVICEINIT_CONFIG_INIT(&before);
  status = AcxDeviceInitInitialize(*init, &before);
  if (!NT_SUCCESS(status)) return status;
  if (child) {
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&power);
    power.EvtDevicePrepareHardware = PiaoipPrepareHardware;
    power.EvtDeviceReleaseHardware = PiaoipReleaseHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(*init, &power);
  }
  WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, PIAOIP_DEVICE_CONTEXT);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  if (child) attributes.EvtCleanupCallback = PiaoipChildCleanup;
  status = WdfDeviceCreate(init, &attributes, &device);
  if (!NT_SUCCESS(status)) return status;
  *result = device;
  PiaoipDeviceContext(device)->is_child = child;
  WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
  attributes.ParentObject = device;
  status = WdfWaitLockCreate(&attributes, &PiaoipDeviceContext(device)->lock);
  if (!NT_SUCCESS(status)) return status;
  ACX_DEVICE_CONFIG_INIT(&after);
  return AcxDeviceInitialize(device, &after);
}

NTSTATUS PiaoipDeviceAdd(WDFDRIVER driver, PWDFDEVICE_INIT init) {
  const UNICODE_STRING security = RTL_CONSTANT_STRING(L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
  WDF_FILEOBJECT_CONFIG files;
  WDF_OBJECT_ATTRIBUTES attributes;
  WDF_IO_QUEUE_CONFIG queue;
  WDFDEVICE device;
  NTSTATUS status;
  UNREFERENCED_PARAMETER(driver);
  /* SYSTEM owns one file handle per board. Ordinary applications access ACX
     endpoints. Ownership is checked per file, never by the selected UI card. */
  WdfDeviceInitSetExclusive(init, FALSE);
  WdfDeviceInitSetCharacteristics(init, FILE_AUTOGENERATED_DEVICE_NAME | FILE_DEVICE_SECURE_OPEN, FALSE);
  status = WdfDeviceInitAssignSDDLString(init, &security);
  if (!NT_SUCCESS(status)) return status;
  WDF_FILEOBJECT_CONFIG_INIT(&files, ReyFileCreate, WDF_NO_EVENT_CALLBACK, PiaoipFileCleanup);
  WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, REY_FILE_CONTEXT);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  WdfDeviceInitSetFileObjectConfig(init, &files, &attributes);
  status = InitializeDevice(&init, FALSE, &device);
  if (!NT_SUCCESS(status)) return status;
  status = WdfDeviceCreateDeviceInterface(device, &GUID_PIAOIP_CONTROL, NULL);
  if (!NT_SUCCESS(status)) return status;
  /* Different boards can exchange PCM concurrently. Each child has its own
     PCM lock; root's bounded ownership lock is released before PCM work. */
  WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue, WdfIoQueueDispatchParallel);
  queue.EvtIoDeviceControl = PiaoipIoControl;
  WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
  attributes.ExecutionLevel = WdfExecutionLevelPassive;
  return WdfIoQueueCreate(device, &queue, &attributes, WDF_NO_HANDLE);
}

VOID ReyFileCreate(WDFDEVICE device, WDFREQUEST request, WDFFILEOBJECT file) {
  REY_FILE_CONTEXT *f = ReyFileContext(file);
  f->root = device;
  f->slot = PIAOIP_DEVICE_LIMIT;
  f->closing = FALSE;
  WdfRequestComplete(request, STATUS_SUCCESS);
}

static VOID ReleaseReservation(WDFDEVICE root, WDFFILEOBJECT file, ULONG slot) {
  PIAOIP_DEVICE_CONTEXT *r = PiaoipDeviceContext(root);
  WdfWaitLockAcquire(r->lock, NULL);
  RtlZeroMemory(&r->children[slot], sizeof(r->children[slot]));
  ReyFileContext(file)->slot = PIAOIP_DEVICE_LIMIT;
  WdfWaitLockRelease(r->lock);
  WdfObjectDereference(file);
}

NTSTATUS PiaoipCreateChild(WDFDEVICE root, WDFFILEOBJECT file, const PIAOIP_BRIDGE_PROFILE *profile) {
  const UNICODE_STRING id = RTL_CONSTANT_STRING(L"REY\\Audio");
  const UNICODE_STRING description = RTL_CONSTANT_STRING(L"Rey Audio 8x8");
  const UNICODE_STRING location = RTL_CONSTANT_STRING(L"USB / AoIP");
  PIAOIP_DEVICE_CONTEXT *r = PiaoipDeviceContext(root);
  REY_FILE_CONTEXT *f = ReyFileContext(file);
  PWDFDEVICE_INIT init = NULL;
  WDFDEVICE child = NULL;
  UNICODE_STRING instance, container;
  WCHAR instance_text[33], container_text[39];
  NTSTATUS status;
  ULONG slot = PIAOIP_DEVICE_LIMIT, i, c = 0;
  WdfWaitLockAcquire(r->lock, NULL);
  if (f->closing || f->slot != PIAOIP_DEVICE_LIMIT) {
    WdfWaitLockRelease(r->lock);
    return STATUS_DEVICE_BUSY;
  }
  for (i = 0; i < PIAOIP_DEVICE_LIMIT; ++i) {
    if (r->children[i].owner && RtlCompareMemory(r->children[i].device_id, profile->device_id, 32) == 32) {
      WdfWaitLockRelease(r->lock);
      return STATUS_OBJECT_NAME_COLLISION;
    }
    if (!r->children[i].owner && slot == PIAOIP_DEVICE_LIMIT) slot = i;
  }
  if (slot == PIAOIP_DEVICE_LIMIT) {
    WdfWaitLockRelease(r->lock);
    return STATUS_INSUFFICIENT_RESOURCES;
  }
  WdfObjectReference(file);
  r->children[slot].owner = file;
  RtlCopyMemory(r->children[slot].device_id, profile->device_id, 32);
  f->slot = slot;
  WdfWaitLockRelease(r->lock);

  init = WdfPdoInitAllocate(root);
  if (!init) { status = STATUS_INSUFFICIENT_RESOURCES; goto failed; }
  status = WdfPdoInitAssignDeviceID(init, &id);
  if (!NT_SUCCESS(status)) goto failed;
  status = WdfPdoInitAddDeviceText(init, &description, &location, 0x0409);
  if (!NT_SUCCESS(status)) goto failed;
  WdfPdoInitSetDefaultLocale(init, 0x0409);
  for (i = 0; i < 32; ++i) instance_text[i] = (WCHAR)profile->device_id[i];
  instance_text[32] = 0;
  RtlInitUnicodeString(&instance, instance_text);
  status = WdfPdoInitAssignInstanceID(init, &instance);
  if (!NT_SUCCESS(status)) goto failed;
  /* A stable, distinct container per board groups its endpoint pairs together
     and keeps the same Windows identity when its USB/LAN route is changed. */
  container_text[c++] = L'{';
  for (i = 0; i < 32; ++i) {
    if (i == 8 || i == 12 || i == 16 || i == 20) container_text[c++] = L'-';
    container_text[c++] = instance_text[i];
  }
  container_text[c++] = L'}'; container_text[c] = 0;
  RtlInitUnicodeString(&container, container_text);
  status = WdfPdoInitAssignContainerID(init, &container);
  if (!NT_SUCCESS(status)) goto failed;
  status = WdfPdoInitAssignRawDevice(init, &GUID_DEVCLASS_MEDIA);
  if (!NT_SUCCESS(status)) goto failed;
  status = InitializeDevice(&init, TRUE, &child);
  if (!NT_SUCCESS(status)) goto failed;
  PiaoipDeviceContext(child)->root = root;
  PiaoipDeviceContext(child)->owner = file;
  PiaoipDeviceContext(child)->device_slot = slot;
  PiaoipDeviceContext(child)->profile = *profile;
  PiaoipDeviceContext(child)->stats.size = sizeof(PIAOIP_BRIDGE_STATS);
  PiaoipDeviceContext(child)->stats.version = PIAOIP_BRIDGE_VERSION;
  PiaoipDeviceContext(child)->stats.attached = 1;
  status = AcxDeviceAddCircuitDevice(root, child);
  if (!NT_SUCCESS(status)) goto failed;
  WdfWaitLockAcquire(r->lock, NULL);
  r->children[slot].child = child;
  r->children[slot].removing = FALSE;
  i = f->closing;
  WdfWaitLockRelease(r->lock);
  if (i) { (VOID)PiaoipDetachChild(file); return STATUS_FILE_CLOSED; }
  return STATUS_SUCCESS;
failed:
  if (init) WdfDeviceInitFree(init);
  if (child) {
    PiaoipDeviceContext(child)->root = NULL;
    PiaoipDeviceContext(child)->owner = NULL;
    WdfObjectDelete(child);
  }
  ReleaseReservation(root, file, slot);
  return status;
}

WDFDEVICE ReyReferenceChild(WDFFILEOBJECT file) {
  REY_FILE_CONTEXT *f;
  PIAOIP_DEVICE_CONTEXT *r;
  WDFDEVICE child = NULL;
  if (!file) return NULL;
  f = ReyFileContext(file); r = PiaoipDeviceContext(f->root);
  WdfWaitLockAcquire(r->lock, NULL);
  if (!f->closing && f->slot < PIAOIP_DEVICE_LIMIT &&
      r->children[f->slot].owner == file && !r->children[f->slot].removing) {
    child = r->children[f->slot].child;
    if (child) WdfObjectReference(child);
  }
  WdfWaitLockRelease(r->lock);
  return child;
}

NTSTATUS PiaoipDetachChild(WDFFILEOBJECT file) {
  REY_FILE_CONTEXT *f = ReyFileContext(file);
  PIAOIP_DEVICE_CONTEXT *r = PiaoipDeviceContext(f->root);
  WDFDEVICE child = NULL;
  ULONG slot;
  NTSTATUS status = STATUS_SUCCESS;
  WdfWaitLockAcquire(r->lock, NULL);
  slot = f->slot;
  if (slot < PIAOIP_DEVICE_LIMIT && r->children[slot].owner == file && !r->children[slot].removing)
    child = r->children[slot].child;
  if (child) {
    WdfObjectReference(child);
    r->children[slot].removing = TRUE;
    WdfWaitLockAcquire(PiaoipDeviceContext(child)->lock, NULL);
    PiaoipDeviceContext(child)->removing = TRUE;
    WdfWaitLockRelease(PiaoipDeviceContext(child)->lock);
  }
  WdfWaitLockRelease(r->lock);
  if (child) {
    status = AcxDeviceRemoveCircuitDevice(f->root, child);
    if (!NT_SUCCESS(status)) {
      WdfWaitLockAcquire(r->lock, NULL);
      r->children[slot].removing = FALSE;
      WdfWaitLockAcquire(PiaoipDeviceContext(child)->lock, NULL);
      PiaoipDeviceContext(child)->removing = FALSE;
      WdfWaitLockRelease(PiaoipDeviceContext(child)->lock);
      WdfWaitLockRelease(r->lock);
    }
    WdfObjectDereference(child);
  }
  return status;
}

VOID PiaoipChildCleanup(WDFOBJECT object) {
  PIAOIP_DEVICE_CONTEXT *c = PiaoipDeviceContext((WDFDEVICE)object);
  if (c->lock) {
    WdfWaitLockAcquire(c->lock, NULL); c->removing = TRUE; WdfWaitLockRelease(c->lock);
  }
  if (c->root && c->owner) {
    PIAOIP_DEVICE_CONTEXT *r = PiaoipDeviceContext(c->root);
    WDFFILEOBJECT owner = c->owner;
    WdfWaitLockAcquire(r->lock, NULL);
    if (r->children[c->device_slot].owner == owner) {
      RtlZeroMemory(&r->children[c->device_slot], sizeof(r->children[c->device_slot]));
      ReyFileContext(owner)->slot = PIAOIP_DEVICE_LIMIT;
    }
    WdfWaitLockRelease(r->lock);
    c->owner = NULL;
    WdfObjectDereference(owner);
  }
}

VOID PiaoipFileCleanup(WDFFILEOBJECT file) {
  REY_FILE_CONTEXT *f = ReyFileContext(file);
  PIAOIP_DEVICE_CONTEXT *r = PiaoipDeviceContext(f->root);
  WdfWaitLockAcquire(r->lock, NULL); f->closing = TRUE; WdfWaitLockRelease(r->lock);
  (VOID)PiaoipDetachChild(file);
}

NTSTATUS PiaoipPrepareHardware(WDFDEVICE device, WDFCMRESLIST raw, WDFCMRESLIST translated) {
  PIAOIP_DEVICE_CONTEXT *d = PiaoipDeviceContext(device);
  NTSTATUS status = STATUS_SUCCESS;
  ULONG slot;
  UNREFERENCED_PARAMETER(raw); UNREFERENCED_PARAMETER(translated);
  if (d->circuits_added) return STATUS_SUCCESS;
  for (slot = 0; slot < PIAOIP_ENDPOINT_SLOTS; ++slot) {
    if (!piaoip_endpoint_channels(slot, d->profile.inputs, d->profile.outputs)) continue;
    status = PiaoipCreateCircuit(device, slot, &d->circuits[slot]);
    if (!NT_SUCCESS(status)) break;
    status = AcxDeviceAddCircuit(device, d->circuits[slot]);
    if (!NT_SUCCESS(status)) { WdfObjectDelete(d->circuits[slot]); d->circuits[slot] = NULL; break; }
  }
  if (!NT_SUCCESS(status)) {
    for (slot = 0; slot < PIAOIP_ENDPOINT_SLOTS; ++slot)
      if (d->circuits[slot]) { (VOID)AcxDeviceRemoveCircuit(device, d->circuits[slot]); d->circuits[slot] = NULL; }
    return status;
  }
  d->circuits_added = TRUE;
  return STATUS_SUCCESS;
}

NTSTATUS PiaoipReleaseHardware(WDFDEVICE device, WDFCMRESLIST translated) {
  PIAOIP_DEVICE_CONTEXT *d = PiaoipDeviceContext(device);
  ULONG slot;
  UNREFERENCED_PARAMETER(translated);
  for (slot = 0; slot < PIAOIP_ENDPOINT_SLOTS; ++slot)
    if (d->circuits[slot]) { (VOID)AcxDeviceRemoveCircuit(device, d->circuits[slot]); d->circuits[slot] = NULL; }
  d->circuits_added = FALSE;
  return STATUS_SUCCESS;
}
